name: Gatling performance tests

on:
    workflow_run:
      workflows: [ 'Gatling tests' ]
      types:
        - completed

    # trigger workflow manually
    workflow_dispatch:
      inputs:
        environment:
          description: 'environment to run tests against'
          required: true
          default: 'staging'

jobs:
  test-run:
    name: build and install env
    runs-on: ubuntu-latest
    steps:
      # checkout project to runner
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run gatling tests
        run : ./scripts/run_local.sh
