name: Gatling performance tests

on:
    workflow_run:
      workflows: [ 'Gatling tests' ]
      types:
        - completed

    # trigger workflow manually
    workflow_dispatch:
      inputs:
        environment:
          description: 'environment to run tests against'
          required: true
          default: 'staging'

jobs:
  test-run:
    name: build and install env
    runs-on: ubuntu-latest
    steps:
      - name: Set environment
        env:
          defaultEnv: 'staging'
      # checkout project to runner
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run gatling tests
        run : ./scripts/start_simulation.sh https://cloud.gatling.io .vfelccKq8oOVIEN2XZ_MzSmHwOS7.0Am0EvzfUMoC9dsmcldGcFuDplpc1pGj5sN 43f77d06-f3b4-4f09-8034-b2af792169ed
